### ISSUE TITLE
Is it a library or a framework ?

### ISSUE THREAD

**Issue by jeremyfourna** [ltoussaint/domscript#1]

**Comment by ltoussaint** [comment]
I see it as a framework, when using it you have to use a specific OOP implementation which is not the javascript standard.
It's inspired by Actionscript3 language.

For more details, the project is composed of 2 parts.
- core.js : based on underscorejs, its a library given methods to manage events, make ajax requests and providing a specific OOP implementation.
- domElement.js : the final goal is to give classes helping you to build and manipulate DOM. By using it you have to use the specific OOP system and other methods from core.js

**Comment by jeremyfourna** [comment]
OK thanks for your help
